services:
  backend:
    build:
      context: ./backend/
      target: development
    volumes:
      - ./backend:/backend
      - ./backend/node_modules:/backend/node_modules
    env_file:
      - ./backend/.env
    command: npm run start:dev
    ports:
      - 3001:3001
